name: Test

on:
  push:
    branches:
      - main

env:
  SQLX_VERSION: 0.7.4
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: todo
          POSTGRES_PASSWORD: password
          POSTGRES_DB: todo
        ports:
          - 5432:5432
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Rust Cache Action
        uses: Swatinem/rust-cache@v2
      - name: Install sqlx-cli
        run:
            cargo install sqlx-cli
            --version=${{ env.SQLX_VERSION }}
            --features "rustls,postgres"
            --no-default-features
            --locked
      - name: Install postgresql-client
        run: sudo apt-get update && sudo apt-get install postgresql-client -y
      - name: Migrate database
        run: SKIP_DOCKER=true ./scripts/setup_db.sh
      - name: Run tests
        env:
          DATABASE_URL: postgres://todo:password@localhost:5432/todo
        run: cargo test

